### ISSUE TITLE
gam error 10764.

### ISSUE THREAD

**Issue by cfosven** [GAM-team/GAM#1495]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. I have
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki I am

Full steps to reproduce the issue:
1.trying to update users images individually and in bulk using:

gam user adele@cfo360.co.uk update photo "G:\Shared drives\General Folders\Letterheads\coverimage.jpg"
gam csv emailphotos.csv gam user ~email update photo ~photos
2. first one returns:

Traceback (most recent call last):
  File "gam\__main__.py", line 49, in <module>
  File "gam\__main__.py", line 44, in main
  File "gam\__init__.py", line 12107, in ProcessGAMCommand
  File "gam\__init__.py", line 2587, in doPhoto
  File "gam\__init__.py", line 1004, in buildGAPIObject
  File "gam\__init__.py", line 932, in getValidOauth2TxtCredentials
  File "gam\auth\oauth.py", line 474, in refresh
  File "gam\auth\oauth.py", line 482, in _locked_refresh
  File "google\oauth2\credentials.py", line 302, in refresh
  File "google\oauth2\reauth.py", line 347, in refresh_grant
  File "google\oauth2\_client.py", line 60, in _handle_error_response
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
[16732] Failed to execute script '__main__' due to unhandled exception!
second one on last attempt:

Using 25 processes...
Finished 2 of 46 processes.
Finished 15 of 46 processes.
Finished 27 of 46 processes.
Finished 38 of 46 processes.

but nothing changed. 

 version
 
 GAM 6.17 - https://git.io/gam - pyinstaller
Jay Lee <jay0lee@gmail.com>
Python 3.10.2 64-bit final
google-api-python-client 2.39.0
Windows 10 10.0.19044 SP0 Multiprocessor Free AMD64
Path: C:\GAM

Expected outcome (what are you trying to do?

update the images

Actual outcome (what errors or bad behavior do you see instead?):

see above. did come across this https://github.com/GAM-team/GAM/issues/1174

is it the same?

**Comment by jay0lee** [comment]
closing as this issue should be fixed in latest GAM7 release.
