### ISSUE TITLE
OAuth fails

### ISSUE THREAD

**Issue by sps-k12** [GAM-team/GAM#1499]
I downloaded gam-6.18-windows-x86_64.msi and installed it on a windows server 2016 standard that has never had gam installed on it before.
I skipped the scopes because it consistently failed. 
After installation completed, I ran the command gam oauth create myemail@mydomain.com

The results were:
IMPORTANT: If you get a browser error that the site can't be reached AFTER you
click the Allow button, copy the URL from the browser where the error occurred
and paste that here instead.

Enter verification code or browser URL: Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "gam\auth\oauth.py", line 572, in _wait_for_http_client
AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "gam\__main__.py", line 49, in <module>
  File "gam\__main__.py", line 44, in main
  File "gam\__init__.py", line 11743, in ProcessGAMCommand
  File "gam\__init__.py", line 10380, in createOAuth
  File "gam\__init__.py", line 10408, in doRequestOAuth
  File "gam\auth\oauth.py", line 379, in from_client_secrets_file
  File "gam\auth\oauth.py", line 316, in from_client_secrets
  File "gam\auth\oauth.py", line 630, in run_dual
  File "<string>", line 2, in __getitem__
  File "multiprocessing\managers.py", line 833, in _callmethod
KeyError: 'code'
[888] Failed to execute script '__main__' due to unhandled exception!

**Comment by jay0lee** [comment]
closing as this issue should be fixed in latest GAM7 release.
