### ISSUE TITLE
Cannot create gam project with fresh install of 6.18 code

### ISSUE THREAD

**Issue by sps-k12** [GAM-team/GAM#1500]
I downloaded a fresh copy of gam-6.18-windows-x86_64.msi and installed it for the first time on a server 2012 standard that has never had gam installed on it before.  It couldn't even create the project.  I ran the command gam create project and get this response:

Enter verification code or browser URL: Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "gam\auth\oauth.py", line 572, in _wait_for_http_client
AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "gam\__main__.py", line 49, in <module>
  File "gam\__main__.py", line 44, in main
  File "gam\__init__.py", line 11350, in ProcessGAMCommand
  File "gam\__init__.py", line 7540, in doCreateProject
  File "gam\__init__.py", line 7422, in _getLoginHintProjectId
  File "gam\__init__.py", line 7047, in getCRMService
  File "gam\auth\oauth.py", line 316, in from_client_secrets
  File "gam\auth\oauth.py", line 630, in run_dual
  File "<string>", line 2, in __getitem__
  File "multiprocessing\managers.py", line 833, in _callmethod
KeyError: 'code'
[9100] Failed to execute script '__main__' due to unhandled exception!

**Comment by jay0lee** [comment]
Please only file one issue.
