### ISSUE TITLE
GAM 6.30 Upgrade Reauthentication Error

### ISSUE THREAD

**Issue by lotspaih** [GAM-team/GAM#1574]
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue. CONFIRMED
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki CONFIRMED

Full steps to reproduce the issue:
1. Upgraded to GAM 6.30 from 6.25 on a Windows 10 system
2. At command line I ran "gam.exe info domain"
3. Received error message below

Expected outcome (what are you trying to do?):

Test that the GAM 6.30 upgrade worked by retrieving domain information

Actual outcome (what errors or bad behavior do you see instead?):

C:\GAM> .\gam.exe info domain
Traceback (most recent call last):
  File "gam\__main__.py", line 49, in <module>
  File "gam\__main__.py", line 44, in main
  File "gam\__init__.py", line 11624, in ProcessGAMCommand
  File "gam\gapi\directory\domains.py", line 25, in info
  File "gam\gapi\directory\customer.py", line 18, in doGetCustomerInfo
  File "gam\gapi\directory\__init__.py", line 5, in build
  File "gam\__init__.py", line 1078, in buildGAPIObject
  File "gam\__init__.py", line 1006, in getValidOauth2TxtCredentials
  File "gam\auth\oauth.py", line 477, in refresh
  File "gam\auth\oauth.py", line 485, in _locked_refresh
  File "google\oauth2\credentials.py", line 302, in refresh
  File "google\oauth2\reauth.py", line 334, in refresh_grant
google.auth.exceptions.RefreshError: Reauthentication is needed. Please run `gcloud auth login --update-adc` to reauthenticate.
[8652] Failed to execute script '__main__' due to unhandled exception!

Had GAM 6.25 installed on a separate Windows Server 2016 system and now it too is giving me the same error message. I also don't understand how to run the "gcloud" command? Thanks!

**Comment by taers232c** [comment]
Mark,

Try:
gam oauth delete
gam oauth create

Ross
----
Ross Scroggs
***@***.***

**Comment by lotspaih** [comment]
Thank you, Ross! That resolved my authentication issue.
