### ISSUE TITLE
3.4 cannot find oauth2service.json on 'gam user me@domain.com show calendars'

### ISSUE THREAD

**Issue by Roalaz** [GAM-team/GAM#19]
I got this error after using the 'gam user me@domain.com show calendars' command:

Traceback (most recent call last):
  File "./gam.py", line 7496, in <module>
    showCalendars(users)
  File "./gam.py", line 1565, in showCalendars
    cal = buildGAPIServiceObject(u'calendar', user)
  File "./gam.py", line 580, in buildGAPIServiceObject
    json_string = open(oauth2servicefilejson).read()
IOError: [Errno 2] No such file or directory: u'/Users/roald/Project/gam2/oauth2service.json'

Every other command I tried works flawlessly. A strange bug or am I doing something very wrong here? This is on OSX Mavericks using gam 3.4 (I didn't see anything related to this in the changelog for 3.41 so I didn't think upgrading would solve this instantly).

**Comment by krispayne** [comment]
I'm having this issue on 3.43:

    ~ ❯ gam version
    Dito GAM 3.43 - http://git.io/gam
    Jay Lee <jay0lee@gmail.com>
    Python 2.7.9 64-bit final
    google-api-python-client 1.3.1
    Darwin-14.1.0-x86_64-i386-64bit x86_64
    Path: /Users/#######/gam/
    ~ ❯ gam user ####### show calendars
    Traceback (most recent call last):
      File "/Users/#######/gam/gam.py", line 7597, in <module>
        showCalendars(users)
      File "/Users/#######/gam/gam.py", line 1570, in showCalendars
        cal = buildGAPIServiceObject(u'calendar', user)
      File "/Users/#######/gam/gam.py", line 596, in buildGAPIServiceObject
        credentials = oauth2client.client.SignedJwtAssertionCredentials(SERVICE_ACCOUNT_EMAIL, key, scope=scope, sub=act_as)
      File "/Users/#######/gam/oauth2client/util.py", line 129, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/Users/#######/gam/oauth2client/client.py", line 1354, in __init__
        _RequireCryptoOrDie()
      File "/Users/#######/gam/oauth2client/client.py", line 1308, in _RequireCryptoOrDie
        raise CryptoUnavailableError('No crypto library available')
    oauth2client.client.CryptoUnavailableError: No crypto library available
    ~ ❯

**Comment by lqkme2** [comment]
Google brought me here:

```
~ >> gam version
Dito GAM 3.43 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.9 64-bit final
google-api-python-client 1.3.1
Darwin-14.3.0-x86_64-i386-64bit x86_64
Path: /Users/###/scratch/gam/
 ~ >> gam user user@domain.com show filelist
Traceback (most recent call last):
  File "/Users/###/scratch/gam/gam.py", line 7605, in <module>
    showDriveFiles(users)
  File "/Users/###/scratch/gam/gam.py", line 1879, in showDriveFiles
    drive = buildGAPIServiceObject(u'drive', user)
  File "/Users/###/scratch/gam/gam.py", line 596, in buildGAPIServiceObject
    credentials = oauth2client.client.SignedJwtAssertionCredentials(SERVICE_ACCOUNT_EMAIL, key, scope=scope, sub=act_as)
  File "/Users/###/scratch/GAM/oauth2client/util.py", line 129, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/###/scratch/GAM/oauth2client/client.py", line 1354, in __init__
    _RequireCryptoOrDie()
  File "/Users/###/scratch/GAM/oauth2client/client.py", line 1308, in _RequireCryptoOrDie
    raise CryptoUnavailableError('No crypto library available')
oauth2client.client.CryptoUnavailableError: No crypto library available
```
 `gam info user` and ` gam info user user@domian.com` works fine for example. I even scraped the `GAM` folder, resynced with GitHub for OS X, recreated client_secrets.json, oauth2service.json and oauth2service.p12, modified "manage API client access", and reaccepted access for the app from Google.
